### ISSUE TITLE
Refund amount not displayed for multiple orders  in “Total” column of the admin’s backend order section. 

### ISSUE THREAD

**Issue by Susmita-dualcube** [wcmarketplace/dc-woocommerce-multi-vendor#163]
To explain the issue - When any vendor refunds his order ( order containning multiple vendor’s products) the refunded amount is not reflected in the parent order id and “Total” column of the admin’s backend order section.   

https://www.loom.com/share/23e7abaf01434582b0fee016860bbf50 

Steps to reproduce the behaviour - Place an order containing products of two or more vendors. Refund any vendor’s product from his dashboard. Go to admin’s order section’s backend (i.e, WooCommerce >> Orders) and view the “Total” column. The refunded product’s amount is not reduced from the total amount. It still displays the amount before the product is refunded. Also, the parent order details does not reflects the refunded product’s amount. 

![FireShot Capture 012 - Screenshot by Lightshot - prnt sc](https://user-images.githubusercontent.com/57519087/69356545-a37b6200-0ca9-11ea-87e2-db4712fc6b90.png)

Expected behaviour - When any vendor refunds his order (order containing multiple vendor’s products), the “Total” column of the admin’s order section’s backend (i.e., WooCommerce >> Orders) should display the deducted amount obtained after processing the refund. Also, the parent order id should reflect the refunded order details.

**Comment by itzmekhokan** [comment]
@Susmita-dualcube @cool-raju

**Comment by moumitahalder** [comment]
I faced the same issue. 
**To Reproduce the issue**
- Place an order with products from more than one vendor
![Screenshot](https://user-images.githubusercontent.com/28754174/71235088-1b788e80-2321-11ea-9c9d-eb1d48901d4a.png)

- Goto admin order page and check the total order amount
![Screenshot (1)](https://user-images.githubusercontent.com/28754174/71235094-1fa4ac00-2321-11ea-90b5-aa226553176c.png)

- Goto any vendor's order page
- Refund an order
https://www.loom.com/share/0b99e10c53e34f88b8a5a50d09c91128
- Now go to admin order page again, you can see the order total didn't reflect the refunded amount.
![Screenshot (2)](https://user-images.githubusercontent.com/28754174/71235105-2fbc8b80-2321-11ea-8087-bfda525fa6e1.png)

**Expected Behavior**
- The total order amount after refund should display the updated value
