### ISSUE TITLE
Product count empty

### ISSUE THREAD

**Issue by blueprin4** [wcmarketplace/dc-woocommerce-multi-vendor#651]
When on wcmp->vendor tab and clicking on product count the next page return blank.  I narrow down the issue is that it pulls based on the display name instead of store slug.
![product-count](https://user-images.githubusercontent.com/10341681/106959399-37dfb200-6700-11eb-91b4-e029dc8028ce.png)

**Comment by srutakirty** [comment]
@blueprin4 we have tested it at our end and it is working fine as you can see here https://www.loom.com/share/b8982cb300aa4a10adf6529e0f26a354

Kindly check the same at your end and if you still face any issue kindly share a video of the issue that you are facing so that we can guide you accordingly.
