### ISSUE TITLE
Manually adding vendors issue

### ISSUE THREAD

**Issue by Tangol** [wcmarketplace/dc-woocommerce-multi-vendor#678]
I'm testing **v3.5.18** on **WP 5.6.1** and I've tried to **Add New Vendor** from the wp-admin, but after I enter all the details and click on **Add New**, the page refreshes and no vendor gets added.

localhost
Apache 2.4
PHP 7.2.34
MySQL 5.6.48

**Comment by moumitahalder** [comment]
Hi we checked the flow on our end, as you can see here : https://www.loom.com/share/a6f1ac23494144bdb683142948f5f234, we didn't face any issue on our end. 

There might be some issue on your site, due to plugin/theme conflict. Just to be sure, please disable all the plugins except WooCommerce, WCMp and check the flow again.

Please do keep us posted.

**Comment by Tangol** [comment]
Have a look: https://drive.google.com/file/d/1Iz9UEoN5lXW9YE5wwbHPIjposMgapMxS/view
Does the email field have some sort of validation or does it try to send am email when the account is created?
Because I'm testing on localhost and no SMTP was setup.

**Comment by cool-raju** [comment]
Hi @Tangol 
SMTP setup doesn't need to create a vendor. You may have some other conflict on your end.
